#!/usr/bin/env bash
# .zcp/lib/bootstrap/import-gen.sh
# Generates import.yml for bootstrap

# Managed service hostname conventions
get_managed_hostname() {
    local service_type="$1"
    case "$service_type" in
        postgresql*|mysql*|mariadb*|mongodb*) echo "db" ;;
        valkey*|keydb*) echo "cache" ;;
        rabbitmq*|nats*) echo "queue" ;;
        elasticsearch*) echo "search" ;;
        minio*) echo "storage" ;;
        *) echo "${service_type%%@*}" ;;
    esac
}

# Get latest version for service type (from recipe-search or defaults)
get_service_version() {
    local service_type="$1"

    # Check if recipe_review.json exists and has version info
    if [ -f "/tmp/recipe_review.json" ]; then
        local version
        version=$(jq -r --arg t "$service_type" \
            '.patterns[$t].version // empty' /tmp/recipe_review.json 2>/dev/null)
        if [ -n "$version" ]; then
            echo "$version"
            return
        fi
    fi

    # Defaults (agent should run recipe-search first!)
    case "$service_type" in
        go) echo "go@1" ;;
        nodejs) echo "nodejs@22" ;;
        python) echo "python@3.12" ;;
        php) echo "php-nginx@8.4" ;;
        rust) echo "rust@1" ;;
        bun) echo "bun@1" ;;
        java) echo "java@21" ;;
        dotnet) echo "dotnet@8" ;;
        postgresql) echo "postgresql@17" ;;
        mysql) echo "mysql@8" ;;
        mariadb) echo "mariadb@11" ;;
        valkey) echo "valkey@8" ;;
        keydb) echo "keydb@6" ;;
        rabbitmq) echo "rabbitmq@4" ;;
        nats) echo "nats@2" ;;
        elasticsearch) echo "elasticsearch@8" ;;
        minio) echo "minio@latest" ;;
        mongodb) echo "mongodb@7" ;;
        *) echo "${service_type}@latest" ;;
    esac
}

# Generate import.yml
# Usage: generate_import_yml --runtime go --services postgresql,valkey --prefix api
generate_import_yml() {
    local runtime="" services="" prefix="app" ha_mode="false" output_file="/tmp/bootstrap_import.yml"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --runtime) runtime="$2"; shift 2 ;;
            --services) services="$2"; shift 2 ;;
            --prefix) prefix="$2"; shift 2 ;;
            --ha) ha_mode="true"; shift ;;
            --output) output_file="$2"; shift 2 ;;
            *) shift ;;
        esac
    done

    if [ -z "$runtime" ]; then
        echo "ERROR: --runtime required" >&2
        return 1
    fi

    local runtime_version
    runtime_version=$(get_service_version "$runtime")

    # Start YAML
    {
        echo "# Generated by ZCP Bootstrap"
        echo "# Runtime: $runtime, Services: ${services:-none}, Prefix: $prefix"
        echo "services:"

        # Managed services FIRST with priority: 10
        if [ -n "$services" ]; then
            IFS=',' read -ra SERVICE_ARRAY <<< "$services"
            for svc in "${SERVICE_ARRAY[@]}"; do
                local svc_name="${svc%%:*}"  # Handle :HA suffix
                local svc_ha="false"
                [[ "$svc" == *":HA"* ]] && svc_ha="true"

                local hostname version mode
                hostname=$(get_managed_hostname "$svc_name")
                version=$(get_service_version "$svc_name")
                mode=$( [ "$svc_ha" = "true" ] || [ "$ha_mode" = "true" ] && echo "HA" || echo "NON_HA" )

                echo "  - hostname: $hostname"
                echo "    type: $version"
                echo "    mode: $mode"
                echo "    priority: 10"
                echo ""
            done
        fi

        # Dev runtime - low baseline, use 'zsc scale' before builds
        echo "  - hostname: ${prefix}dev"
        echo "    type: $runtime_version"
        echo "    startWithoutCode: true"
        echo "    verticalAutoscaling:"
        echo "      minRam: 0.5"
        echo "    # NOTE: enableSubdomainAccess NOT valid with startWithoutCode"
        echo "    # Use: zcli service enable-subdomain -S {id} after import"
        echo ""

        # Stage runtime
        echo "  - hostname: ${prefix}stage"
        echo "    type: $runtime_version"
        echo "    startWithoutCode: true"
        echo ""

    } > "$output_file"

    echo "$output_file"
}

export -f get_managed_hostname get_service_version generate_import_yml
