#!/usr/bin/env bash
# .zcp/lib/bootstrap/import-gen.sh
# Generates import.yml for bootstrap

# Managed service hostname conventions
get_managed_hostname() {
    local service_type="$1"
    case "$service_type" in
        postgresql*|mysql*|mariadb*|mongodb*) echo "db" ;;
        valkey*|keydb*) echo "cache" ;;
        rabbitmq*|nats*) echo "queue" ;;
        elasticsearch*) echo "search" ;;
        minio*) echo "storage" ;;
        *) echo "${service_type%%@*}" ;;
    esac
}

# Generate import.yml
# Usage: generate_import_yml --runtime-versions '{"go":"go@1.22"}' --service-versions '{"valkey":"valkey@7.2"}' --prefix app --ha
# Version maps are JSON objects: {"type": "version@X"}
generate_import_yml() {
    local runtime_versions='{}' service_versions='{}' prefixes="app" ha_mode="false" output_file="/tmp/bootstrap_import.yml"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --runtime-versions) runtime_versions="$2"; shift 2 ;;
            --service-versions) service_versions="$2"; shift 2 ;;
            --prefix|--prefixes) prefixes="$2"; shift 2 ;;
            --ha) ha_mode="true"; shift ;;
            --output) output_file="$2"; shift 2 ;;
            *) shift ;;
        esac
    done

    # Extract runtimes and their versions
    local runtime_types
    runtime_types=$(echo "$runtime_versions" | jq -r 'keys[]')

    if [ -z "$runtime_types" ]; then
        echo "ERROR: --runtime-versions required with at least one runtime" >&2
        return 1
    fi

    # Split prefixes
    IFS=',' read -ra prefix_arr <<< "$prefixes"

    local runtime_arr=()
    while IFS= read -r rt; do
        [ -n "$rt" ] && runtime_arr+=("$rt")
    done <<< "$runtime_types"

    local num_runtimes=${#runtime_arr[@]}
    local num_prefixes=${#prefix_arr[@]}

    # If fewer prefixes than runtimes, use runtime name as prefix
    if [ $num_prefixes -lt $num_runtimes ]; then
        for ((i=num_prefixes; i<num_runtimes; i++)); do
            prefix_arr+=("${runtime_arr[$i]}")
        done
    fi

    # Start YAML
    {
        echo "# Generated by ZCP Bootstrap"
        echo "# Versions from docs.zerops.io/data.json"
        echo "services:"

        # Managed services FIRST with priority: 10
        local svc_types
        svc_types=$(echo "$service_versions" | jq -r 'keys[]')

        for svc_name in $svc_types; do
            [ -z "$svc_name" ] && continue

            local hostname version mode
            hostname=$(get_managed_hostname "$svc_name")
            version=$(echo "$service_versions" | jq -r --arg s "$svc_name" '.[$s]')
            mode=$( [ "$ha_mode" = "true" ] && echo "HA" || echo "NON_HA" )

            echo "  - hostname: $hostname"
            echo "    type: $version"
            echo "    mode: $mode"
            echo "    priority: 10"
            echo ""
        done

        # Generate dev/stage pairs for EACH runtime
        for ((i=0; i<num_runtimes; i++)); do
            local rt="${runtime_arr[$i]}"
            local px="${prefix_arr[$i]}"
            local runtime_version
            runtime_version=$(echo "$runtime_versions" | jq -r --arg r "$rt" '.[$r]')

            # Dev runtime
            echo "  - hostname: ${px}dev"
            echo "    type: $runtime_version"
            echo "    startWithoutCode: true"
            echo "    verticalAutoscaling:"
            echo "      minRam: 0.5"
            echo ""

            # Stage runtime
            echo "  - hostname: ${px}stage"
            echo "    type: $runtime_version"
            echo "    startWithoutCode: true"
            echo ""
        done

    } > "$output_file"

    echo "$output_file"
}

export -f get_managed_hostname generate_import_yml
