package workflow

// Goldens-driven scenario tests for atom-corpus-verification (Phase 1
// of plans/atom-corpus-verification-2026-05-02.md). Each canonical
// scenario carries a typed StateEnvelope fixture and a reviewed golden
// file at testdata/atom-goldens/<scenario-id>.md. The render is
// deterministic; comparison is byte-exact (mod trailing newline +
// stripping the optional UNREVIEWED marker).
//
// Two env-var gates:
//   - ZCP_GOLDEN_COMPARE: when set, the comparison test runs. Default
//     (unset) skips with a TODO message — Phase 1 commits leave goldens
//     UNREVIEWED, Phase 2 blesses them and flips the default on.
//   - ZCP_UPDATE_ATOM_GOLDENS: when set, the test regenerates each
//     golden file from the live envelope+corpus. Mutually exclusive
//     with CI=true via guardCIRegenerate (panics if both are set).
//
// goldenScenario is the in-test shape — id, description, envelope
// fixture, and an isExportRender flag that selects the export-aware
// renderer (RenderExportGuidance) over the universal SynthesizeBodies
// path so service-context atoms fire correctly for the 7 export sub-
// status scenarios.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// goldenScenario pins one canonical scenario's id + description +
// envelope fixture. The fixture is the canonical envelope shape Phase 2
// blesses; corpus_pin_density / pin-coverage stay independent concerns.
type goldenScenario struct {
	id          string
	description string
	envelope    StateEnvelope
}

// TestScenarios_GoldenComparison loads every canonical scenario, runs
// Synthesize+render against the live atom corpus, and either compares
// the rendered output to the golden file (default behaviour gated on
// ZCP_GOLDEN_COMPARE) or regenerates the golden file
// (ZCP_UPDATE_ATOM_GOLDENS). Phase 1 commits ship raw outputs marked
// `<!-- UNREVIEWED -->`; Phase 2 strips the marker after blessing each
// scenario's content.
func TestScenarios_GoldenComparison(t *testing.T) {
	t.Parallel()

	corpus, err := LoadAtomCorpus()
	if err != nil {
		t.Fatalf("LoadAtomCorpus: %v", err)
	}

	scenarios := canonicalGoldenScenarios()
	if len(scenarios) == 0 {
		t.Fatal("no canonical scenarios — fixture file is empty; Phase 1 fixture authoring incomplete")
	}

	regenerate := os.Getenv("ZCP_UPDATE_ATOM_GOLDENS") != ""
	compare := os.Getenv("ZCP_GOLDEN_COMPARE") != ""
	if regenerate {
		guardCIRegenerate()
	}
	if !regenerate && !compare {
		t.Skip("TODO: Phase 2 blesses goldens — set ZCP_GOLDEN_COMPARE=1 to enforce, ZCP_UPDATE_ATOM_GOLDENS=1 to regenerate locally")
	}

	for _, scn := range scenarios {
		t.Run(scn.id, func(t *testing.T) {
			t.Parallel()
			actualBody := renderScenarioBody(t, scn.envelope, corpus)
			actualAtomIDs := atomIDsForScenario(t, scn.envelope, corpus)

			if regenerate {
				regenerateGolden(t, scn, actualAtomIDs, actualBody)
				return
			}
			compareGolden(t, scn, actualAtomIDs, actualBody)
		})
	}

	// Coverage map auto-regenerates alongside goldens so it stays in
	// sync. Comparison runs read it indirectly via the Phase 4
	// coverage-gate test (covered later in plan §4); this Phase 1
	// emitter just keeps the file fresh.
	if regenerate {
		t.Run("_coverage-map", func(t *testing.T) {
			regenerateCoverageMap(t, scenarios, corpus)
		})
	}
}

// regenerateCoverageMap walks every scenario, records which atoms it
// renders, and writes a markdown table to
// testdata/atom-goldens/_coverage-map.md. Atoms that appear in zero
// scenarios get a TODO line — Phase 4's coverage gate test will fail
// until each unflagged atom has scenario coverage or carries the
// coverageExempt: frontmatter field.
func regenerateCoverageMap(t *testing.T, scenarios []goldenScenario, corpus []KnowledgeAtom) {
	t.Helper()
	atomScenarios := make(map[string][]string, len(corpus))
	for _, scn := range scenarios {
		ids := atomIDsForScenario(t, scn.envelope, corpus)
		for _, id := range ids {
			atomScenarios[id] = append(atomScenarios[id], scn.id)
		}
	}

	corpusIDs := make([]string, 0, len(corpus))
	for _, a := range corpus {
		corpusIDs = append(corpusIDs, a.ID)
	}
	sort.Strings(corpusIDs)

	var sb strings.Builder
	sb.WriteString("# Atom coverage map\n\n")
	sb.WriteString("Auto-generated by `TestScenarios_GoldenComparison` ")
	sb.WriteString("with `ZCP_UPDATE_ATOM_GOLDENS=1`. Lists every atom in ")
	sb.WriteString("the corpus and which canonical scenarios render it.\n\n")
	sb.WriteString("Atoms with zero scenarios are flagged `TODO: explicit ")
	sb.WriteString("decision required` — Phase 4 coverage gate test (plan ")
	sb.WriteString("`plans/atom-corpus-verification-2026-05-02.md` §4.5) ")
	sb.WriteString("will fail until each one either gains scenario coverage ")
	sb.WriteString("OR carries a `coverageExempt:` frontmatter entry with ")
	sb.WriteString("rationale.\n\n")
	sb.WriteString("| Atom ID | Scenario count | Scenarios |\n")
	sb.WriteString("|---|---|---|\n")
	for _, id := range corpusIDs {
		scns := atomScenarios[id]
		if len(scns) == 0 {
			sb.WriteString("| `")
			sb.WriteString(id)
			sb.WriteString("` | 0 | TODO: explicit decision required (scenario or `coverageExempt:` frontmatter) |\n")
			continue
		}
		// Stable order in the rendered list.
		sort.Strings(scns)
		fmt.Fprintf(&sb, "| `%s` | %d | %s |\n", id, len(scns), strings.Join(scns, ", "))
	}
	path := filepath.Join(atomGoldensDir, "_coverage-map.md")
	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		t.Fatalf("write coverage map %q: %v", path, err)
	}
	t.Logf("wrote coverage map: %s", path)
}

// renderScenarioBody composes the rendered atom-body output for a
// scenario envelope. Export-active envelopes use RenderExportGuidance
// so the same separator and ordering the production handler uses
// surface in the golden — the golden therefore matches what the agent
// receives via `zerops_workflow workflow="export"`.
func renderScenarioBody(t *testing.T, env StateEnvelope, corpus []KnowledgeAtom) string {
	t.Helper()
	if env.Phase == PhaseExportActive {
		body, err := RenderExportGuidance(env, corpus)
		if err != nil {
			t.Fatalf("RenderExportGuidance: %v", err)
		}
		return body
	}
	bodies, err := SynthesizeBodies(env, corpus)
	if err != nil {
		t.Fatalf("SynthesizeBodies: %v", err)
	}
	return strings.Join(bodies, "\n\n---\n\n")
}

// atomIDsForScenario returns the matched atom IDs in render order
// (NOT sorted — order is the property goldens pin). Mirrors
// renderScenarioBody's path selection.
func atomIDsForScenario(t *testing.T, env StateEnvelope, corpus []KnowledgeAtom) []string {
	t.Helper()
	matches, err := Synthesize(env, corpus)
	if err != nil {
		t.Fatalf("Synthesize: %v", err)
	}
	ids := make([]string, len(matches))
	for i, m := range matches {
		ids[i] = m.AtomID
	}
	return ids
}

// regenerateGolden writes the live render to disk for the given
// scenario. Phase 1 commits ship the resulting file with the
// `<!-- UNREVIEWED -->` marker; Phase 2 blesses by re-running with the
// flag and dropping the marker.
func regenerateGolden(t *testing.T, scn goldenScenario, atomIDs []string, body string) {
	t.Helper()
	path := goldenPathFor(scn.id)
	if err := ensureGoldenDir(path); err != nil {
		t.Fatalf("ensure golden dir: %v", err)
	}
	content := renderGoldenFile(scn.id, scn.description, atomIDs, body, true /* unreviewed */)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write golden %q: %v", path, err)
	}
	t.Logf("wrote golden: %s", path)
}

// compareGolden reads the on-disk golden and asserts the live render
// matches it. Atom-ID order is compared first as a separate check — a
// reorder produces a focused error that doesn't get lost inside a
// large markdown diff. Body comparison strips the optional
// `<!-- UNREVIEWED -->` marker so Phase 2 bless can drop the marker
// without bumping the body byte-comparison.
func compareGolden(t *testing.T, scn goldenScenario, atomIDs []string, body string) {
	t.Helper()
	path := goldenPathFor(scn.id)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %q: %v (regenerate via ZCP_UPDATE_ATOM_GOLDENS=1)", path, err)
	}
	gf, err := parseGoldenFile(path, string(raw))
	if err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if gf.ID != scn.id {
		t.Errorf("%s: golden file id %q does not match scenario id %q", path, gf.ID, scn.id)
	}
	if !slicesEqualString(atomIDs, gf.AtomIDs) {
		t.Errorf("%s: atom ID order mismatch\n  want: %v\n  got:  %v", path, gf.AtomIDs, atomIDs)
		return
	}
	wantBody := stripUnreviewedMarker(gf.Body)
	gotBody := body
	if !strings.HasSuffix(gotBody, "\n") {
		gotBody += "\n"
	}
	if !strings.HasSuffix(wantBody, "\n") {
		wantBody += "\n"
	}
	if wantBody != gotBody {
		t.Errorf("%s: body mismatch (length want=%d got=%d)\n--- want body:\n%s\n--- got body:\n%s",
			path, len(wantBody), len(gotBody), wantBody, gotBody)
	}
}

// stripUnreviewedMarker drops the `<!-- UNREVIEWED -->` marker line
// (with optional surrounding blank lines) from the start of a body so
// Phase 2 bless can remove it without breaking byte-exact comparison.
func stripUnreviewedMarker(body string) string {
	lines := strings.Split(body, "\n")
	out := make([]string, 0, len(lines))
	stripped := false
	for _, line := range lines {
		if !stripped && strings.Contains(line, "<!-- UNREVIEWED -->") {
			stripped = true
			continue
		}
		// After stripping, drop one leading blank line if present.
		if stripped && len(out) == 0 && strings.TrimSpace(line) == "" {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// slicesEqualString compares two []string for equality with order. The
// generic `slicesEqual` defined in atom_test.go is constrained to
// `~string`, but its signature requires an explicit type parameter
// when both args are plain `[]string` (the inferred T = string is
// fine, but keeping the helper local keeps file dependencies obvious).
func slicesEqualString(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
