package skillpacks

import (
	"os"
	"regexp"
	"sort"
	"testing"
)

func TestLookup_KnownAndUnknown(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		id     string
		wantOK bool
	}{
		{name: "matt-pocock-skills is known", id: "matt-pocock-skills", wantOK: true},
		{name: "superpowers is known", id: "superpowers", wantOK: true},
		{name: "andrej-karpathy-skills is known", id: "andrej-karpathy-skills", wantOK: true},
		{name: "unknown id", id: "not-a-real-pack", wantOK: false},
		// Retired from the catalog: ZCP already ships Anthropic's agent, so
		// offering Anthropic's own skills as a third-party pack was noise.
		// A manifest-recorded install stays removable (Remove/PackSet do not
		// consult the catalog) — see TestRemove_RetiredPack_StillRemovable
		// and TestPackSet_RetiredPack_RemovableViaSet.
		{name: "anthropic-skills is retired", id: "anthropic-skills", wantOK: false},
		{name: "gstack is deliberately excluded (56MB whole-repo, not a skills collection)", id: "gstack", wantOK: false},
		{name: "empty id", id: "", wantOK: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			pack, ok := Lookup(tt.id)
			if ok != tt.wantOK {
				t.Fatalf("Lookup(%q) ok = %v, want %v", tt.id, ok, tt.wantOK)
			}
			if !ok {
				return
			}
			if pack.ID != tt.id {
				t.Errorf("pack.ID = %q, want %q", pack.ID, tt.id)
			}
			if pack.Ref == "" {
				t.Errorf("pack.Ref is empty for %q", tt.id)
			}
			if pack.Title == "" || pack.Description == "" {
				t.Errorf("pack %q missing title/description", tt.id)
			}
		})
	}
}

// TestCatalog_MattSupportedSet_Exactly21Grouped pins spec-skill-packs.md
// §4.1's exact 21-skill table, transcribed independently from the spec (not
// generated by reading the catalog back): 17 Engineering + 4 Productivity.
// Personal, miscellaneous, in-progress, and deprecated upstream skills must
// never appear. grill-me is deliberately excluded: its upstream body is a
// thin "run /grilling" wrapper, a duplicate picker entry that overlaps
// grilling's own description, and a subset-selection hazard if picked alone.
func TestCatalog_MattSupportedSet_Exactly21Grouped(t *testing.T) {
	t.Parallel()

	wantEngineering := []string{
		"ask-matt", "diagnosing-bugs", "grill-with-docs", "triage",
		"improve-codebase-architecture", "setup-matt-pocock-skills", "tdd",
		"to-spec", "to-tickets", "wayfinder", "implement", "prototype",
		"research", "domain-modeling", "codebase-design", "code-review",
		"resolving-merge-conflicts",
	}
	wantProductivity := []string{"grilling", "handoff", "teach", "writing-great-skills"}

	pack, ok := Lookup("matt-pocock-skills")
	if !ok {
		t.Fatal("matt-pocock-skills missing from catalog")
	}
	if pack.Review != ReviewSkillLevel {
		t.Fatalf("matt-pocock-skills Review = %v, want ReviewSkillLevel", pack.Review)
	}
	if len(pack.Skills) != 21 {
		t.Fatalf("len(pack.Skills) = %d, want 21", len(pack.Skills))
	}

	byCategory := map[string][]string{}
	seenNames := map[string]bool{}
	for _, sk := range pack.Skills {
		if sk.Name == "" || sk.SourcePath == "" || sk.Category == "" || sk.Description == "" {
			t.Errorf("skill %+v missing a required field", sk)
		}
		if seenNames[sk.Name] {
			t.Errorf("duplicate skill name %q in matt-pocock-skills catalog", sk.Name)
		}
		seenNames[sk.Name] = true
		byCategory[sk.Category] = append(byCategory[sk.Category], sk.Name)
	}

	if len(byCategory) != 2 {
		t.Fatalf("categories = %v, want exactly 2 (Engineering, Productivity)", byCategory)
	}
	assertSameSet(t, "Engineering", byCategory["Engineering"], wantEngineering)
	assertSameSet(t, "Productivity", byCategory["Productivity"], wantProductivity)

	for _, sk := range pack.Skills {
		var wantPrefix string
		switch sk.Category {
		case "Engineering":
			wantPrefix = "skills/engineering/"
		case "Productivity":
			wantPrefix = "skills/productivity/"
		}
		if want := wantPrefix + sk.Name; sk.SourcePath != want {
			t.Errorf("skill %q SourcePath = %q, want %q", sk.Name, sk.SourcePath, want)
		}
	}
}

// TestCatalog_SuperpowersSupportedSet_Exactly14 pins spec-skill-packs.md
// §5's exact 14-skill table, transcribed independently from the spec.
func TestCatalog_SuperpowersSupportedSet_Exactly14(t *testing.T) {
	t.Parallel()

	want := []string{
		"test-driven-development",
		"systematic-debugging", "verification-before-completion",
		"brainstorming", "writing-plans", "executing-plans",
		"dispatching-parallel-agents", "requesting-code-review",
		"receiving-code-review", "using-git-worktrees",
		"finishing-a-development-branch", "subagent-driven-development",
		"writing-skills", "using-superpowers",
	}

	pack, ok := Lookup("superpowers")
	if !ok {
		t.Fatal("superpowers missing from catalog")
	}
	if pack.Review != ReviewSkillLevel {
		t.Fatalf("superpowers Review = %v, want ReviewSkillLevel", pack.Review)
	}
	if len(pack.Skills) != 14 {
		t.Fatalf("len(pack.Skills) = %d, want 14", len(pack.Skills))
	}

	got := make([]string, 0, len(pack.Skills))
	seenNames := map[string]bool{}
	for _, sk := range pack.Skills {
		if sk.Name == "" || sk.SourcePath == "" || sk.Category == "" || sk.Description == "" {
			t.Errorf("skill %+v missing a required field", sk)
		}
		if seenNames[sk.Name] {
			t.Errorf("duplicate skill name %q in superpowers catalog", sk.Name)
		}
		seenNames[sk.Name] = true
		got = append(got, sk.Name)
		if want := "skills/" + sk.Name; sk.SourcePath != want {
			t.Errorf("skill %q SourcePath = %q, want %q", sk.Name, sk.SourcePath, want)
		}
	}
	assertSameSet(t, "superpowers", got, want)
}

// TestCatalog_RepositoryLevelPacks_DeclareNoSkillList proves
// andrej-karpathy-skills stays repository-level review (§1): it declares no
// per-skill catalog, so its complete discovered set installs together, unlike
// Matt and Superpowers.
func TestCatalog_RepositoryLevelPacks_DeclareNoSkillList(t *testing.T) {
	t.Parallel()

	for _, id := range []string{"andrej-karpathy-skills"} {
		t.Run(id, func(t *testing.T) {
			t.Parallel()
			pack, ok := Lookup(id)
			if !ok {
				t.Fatalf("%s missing from catalog", id)
			}
			if pack.Review != ReviewRepositoryLevel {
				t.Errorf("%s Review = %v, want ReviewRepositoryLevel", id, pack.Review)
			}
			if len(pack.Skills) != 0 {
				t.Errorf("%s declares %d skills, want 0 (repository-level packs declare no skill list)", id, len(pack.Skills))
			}
		})
	}
}

// assertSameSet fails the test unless got and want contain the same names,
// order-independent.
func assertSameSet(t *testing.T, label string, got, want []string) {
	t.Helper()
	gotSorted := append([]string(nil), got...)
	wantSorted := append([]string(nil), want...)
	sort.Strings(gotSorted)
	sort.Strings(wantSorted)
	if !equalStrings(gotSorted, wantSorted) {
		t.Errorf("%s names = %v, want %v", label, gotSorted, wantSorted)
	}
}

func TestValidIDs_SortedAndMatchesCatalog(t *testing.T) {
	t.Parallel()

	ids := ValidIDs()
	if len(ids) != 3 {
		t.Fatalf("len(ValidIDs()) = %d, want 3", len(ids))
	}
	if !sort.StringsAreSorted(ids) {
		t.Errorf("ValidIDs() = %v, want sorted", ids)
	}
	for _, id := range ids {
		if _, ok := Lookup(id); !ok {
			t.Errorf("ValidIDs() contains %q, but Lookup(%q) failed", id, id)
		}
	}
}

// TestCatalogIDs_MatchWelcomeExtensionAllowlist is the registry contract
// test: internal/content/templates/vscode-bootstrap-welcome.js keeps its
// own PACKS allowlist (a parallel JS enum, since the extension never reads
// Go source), and a source-layout change to one side without the other is
// exactly the class of drift that caused the Matt Pocock discovery failure
// this whole redesign responds to. This test only READS the JS file — it
// never modifies template content.
func TestCatalogIDs_MatchWelcomeExtensionAllowlist(t *testing.T) {
	t.Parallel()

	data, err := os.ReadFile("../content/templates/vscode-bootstrap-welcome.js")
	if err != nil {
		t.Fatalf("read welcome template: %v", err)
	}

	re := regexp.MustCompile(`(?s)const PACKS = \[(.*?)\];`)
	m := re.FindSubmatch(data)
	if m == nil {
		t.Fatal("could not find `const PACKS = [...]` in vscode-bootstrap-welcome.js — has the allowlist been renamed?")
	}
	idRe := regexp.MustCompile(`"([a-z0-9-]+)"`)
	idMatches := idRe.FindAllStringSubmatch(string(m[1]), -1)
	if len(idMatches) == 0 {
		t.Fatal("PACKS array parsed as empty")
	}
	jsIDs := make([]string, 0, len(idMatches))
	for _, im := range idMatches {
		jsIDs = append(jsIDs, im[1])
	}
	sort.Strings(jsIDs)

	goIDs := ValidIDs()
	if len(jsIDs) != len(goIDs) {
		t.Fatalf("welcome.js PACKS = %v, Go catalog = %v — length mismatch", jsIDs, goIDs)
	}
	for i := range goIDs {
		if jsIDs[i] != goIDs[i] {
			t.Errorf("welcome.js PACKS = %v, Go catalog ValidIDs() = %v — must match exactly", jsIDs, goIDs)
			break
		}
	}
}

// TestCatalog_SelectionGranularity_MattSubsetSuperpowersAtomic pins
// spec-skill-packs.md §1's closing rule that selection granularity is an
// axis of its own: both packs are reviewed skill by skill, yet only Matt
// offers a subset (§4.2) while Superpowers installs whole or not at all
// (§5). SelectionAtomic is the zero value, so a newly catalogued pack has
// to opt IN to offering a subset rather than inheriting one by omission.
func TestCatalog_SelectionGranularity_MattSubsetSuperpowersAtomic(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		id       string
		want     SelectionGranularity
		isAtomic bool
	}{
		{id: "matt-pocock-skills", want: SelectionSubset, isAtomic: false},
		{id: "superpowers", want: SelectionAtomic, isAtomic: true},
	} {
		pack, ok := Lookup(tc.id)
		if !ok {
			t.Fatalf("Lookup(%q) not found", tc.id)
		}
		if pack.Selection != tc.want {
			t.Errorf("%s Selection = %v, want %v", tc.id, pack.Selection, tc.want)
		}
		if got := pack.IsAtomic(); got != tc.isAtomic {
			t.Errorf("%s IsAtomic() = %v, want %v", tc.id, got, tc.isAtomic)
		}
	}
}
