package tools

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zeropsio/zcp/internal/workflow"
)

func testFinalizePlan() *workflow.RecipePlan {
	return &workflow.RecipePlan{
		Framework:   "bun",
		Tier:        workflow.RecipeTierMinimal,
		Slug:        "bun-hello-world",
		RuntimeType: "bun@1",
		Research: workflow.ResearchData{
			ServiceType:    "bun",
			PackageManager: "bun",
			HTTPPort:       3000,
			BuildCommands:  []string{"bun install"},
			DeployFiles:    []string{"."},
			StartCommand:   "bun run start",
			NeedsAppSecret: false,
		},
		Targets: []workflow.RecipeTarget{
			{Hostname: "app", Type: "bun@1", Role: "app", Environments: []string{"0", "1", "2", "3", "4", "5"}},
			{Hostname: "db", Type: "postgresql@16", Role: "db", Environments: []string{"0", "1", "2", "3", "4", "5"}},
		},
	}
}

// writeRecipeFiles generates all recipe files in a temp directory using templates + comments.
func writeRecipeFiles(t *testing.T, dir string, plan *workflow.RecipePlan) {
	t.Helper()

	files := workflow.BuildFinalizeOutput(plan)
	for relPath, content := range files {
		fullPath := filepath.Join(dir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			t.Fatal(err)
		}
		// Add comments to import.yaml to meet 30% ratio.
		if filepath.Base(relPath) == "import.yaml" {
			content = addCommentsToYAML(content)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// addCommentsToYAML adds inline comments to YAML content to meet comment ratio.
func addCommentsToYAML(content string) string {
	// Prepend comment block and add per-line comments to meet 30% ratio.
	var result []string
	result = append(result,
		"# Recipe import configuration",
		"# Generated by ZCP recipe workflow",
		"# This file defines the project and services",
		"# for this environment tier",
		"# See the environment README.md for details",
		"# Import this file to create your Zerops project",
	)
	for line := range strings.SplitSeq(content, "\n") {
		result = append(result, line)
		trimmed := strings.TrimSpace(line)
		// Add a comment after every substantive line to ensure ratio.
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") && strings.Contains(trimmed, ":") {
			result = append(result, "  # "+trimmed)
		}
	}
	return strings.Join(result, "\n")
}

func TestCheckRecipeFinalize_ValidOutput(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	writeRecipeFiles(t, dir, plan)

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
	if !result.Passed {
		t.Errorf("expected all checks to pass:")
		for _, c := range result.Checks {
			if c.Status == "fail" {
				t.Errorf("  %s: %s", c.Name, c.Detail)
			}
		}
	}
}

func TestCheckRecipeFinalize_MissingFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	// Don't write any files.

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.Passed {
		t.Error("expected checks to fail when files are missing")
	}

	// Count file existence failures.
	failCount := 0
	for _, c := range result.Checks {
		if c.Status == "fail" {
			failCount++
		}
	}
	// Should have at least 13 file failures (1 main README + 6 import.yaml + 6 env README).
	if failCount < 13 {
		t.Errorf("expected at least 13 failures, got %d", failCount)
	}
}

func TestCheckRecipeFinalize_InvalidYAML(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	writeRecipeFiles(t, dir, plan)

	// Overwrite one import.yaml with invalid YAML.
	badPath := filepath.Join(dir, workflow.EnvFolder(0), "import.yaml")
	if err := os.WriteFile(badPath, []byte("{{invalid yaml"), 0o644); err != nil {
		t.Fatal(err)
	}

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.Passed {
		t.Error("expected checks to fail with invalid YAML")
	}

	found := false
	for _, c := range result.Checks {
		if c.Status == "fail" && c.Name == fmt.Sprintf("%s_import_valid_yaml", workflow.EnvFolder(0)) {
			found = true
			break
		}
	}
	if !found {
		t.Error("expected valid_yaml check to fail")
	}
}

func TestCheckRecipeFinalize_EnvSecrets(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	plan.Research.NeedsAppSecret = true

	writeRecipeFiles(t, dir, plan)

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// The generated templates include envSecrets when NeedsAppSecret is true,
	// so this should pass.
	for _, c := range result.Checks {
		if c.Name != "" && c.Status == "fail" && c.Detail != "" {
			// Check it's not an envSecrets failure.
			if strings.Contains(c.Name, "env_secrets") {
				t.Errorf("envSecrets check should pass: %s", c.Detail)
			}
		}
	}
}

func TestCheckRecipeFinalize_CommentRatio(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()

	// Write files WITHOUT extra comments.
	files := workflow.BuildFinalizeOutput(plan)
	for relPath, content := range files {
		fullPath := filepath.Join(dir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should have comment_ratio failures (templates don't have enough comments).
	hasCommentFail := false
	for _, c := range result.Checks {
		if c.Status == "fail" && strings.Contains(c.Name, "comment_ratio") {
			hasCommentFail = true
			break
		}
	}
	if !hasCommentFail {
		t.Error("expected comment_ratio check to fail for uncommented templates")
	}
}
