package tools

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zeropsio/zcp/internal/workflow"
)

func testFinalizePlan() *workflow.RecipePlan {
	return &workflow.RecipePlan{
		Framework:   "bun",
		Tier:        workflow.RecipeTierMinimal,
		Slug:        "bun-hello-world",
		RuntimeType: "bun@1",
		Research: workflow.ResearchData{
			ServiceType:    "bun",
			PackageManager: "bun",
			HTTPPort:       3000,
			BuildCommands:  []string{"bun install"},
			DeployFiles:    []string{"."},
			StartCommand:   "bun run start",
			NeedsAppSecret: false,
		},
		Targets: []workflow.RecipeTarget{
			{Hostname: "app", Type: "bun@1", Environments: []string{"0", "1", "2", "3", "4", "5"}},
			{Hostname: "db", Type: "postgresql@16", Environments: []string{"0", "1", "2", "3", "4", "5"}},
		},
	}
}

// writeRecipeFiles generates all recipe files in a temp directory using templates + comments.
func writeRecipeFiles(t *testing.T, dir string, plan *workflow.RecipePlan) {
	t.Helper()

	files := workflow.BuildFinalizeOutput(plan)
	// Replace the TODO-scaffold app README with a real-looking one so the
	// scaffold-TODO check passes (the check exists to force agents to overlay
	// the real README from the mount; tests don't have a mount).
	files["appdev/README.md"] = validTestAppREADME()
	for relPath, content := range files {
		fullPath := filepath.Join(dir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			t.Fatal(err)
		}
		// Add comments to import.yaml to meet 30% ratio.
		if filepath.Base(relPath) == "import.yaml" {
			content = addCommentsToYAML(content)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// validTestAppREADME returns a minimal app README with all 3 extract-fragment
// markers and no TODO scaffold text — enough to satisfy the scaffold check.
func validTestAppREADME() string {
	return `# Test Recipe App

<!-- #ZEROPS_EXTRACT_START:intro# -->
A minimal app for testing.
<!-- #ZEROPS_EXTRACT_END:intro# -->

## Integration Guide

<!-- #ZEROPS_EXTRACT_START:integration-guide# -->

### 1. Adding ` + "`zerops.yaml`" + `
Place at repo root.

<!-- #ZEROPS_EXTRACT_END:integration-guide# -->

<!-- #ZEROPS_EXTRACT_START:knowledge-base# -->

### Gotchas
- Test gotcha.

<!-- #ZEROPS_EXTRACT_END:knowledge-base# -->
`
}

// addCommentsToYAML adds inline comments to YAML content to meet comment ratio.
func addCommentsToYAML(content string) string {
	// Prepend comment block and add per-line comments to meet 30% ratio.
	var result []string
	result = append(result,
		"# Recipe import configuration",
		"# Generated by ZCP recipe workflow",
		"# This file defines the project and services",
		"# for this environment tier",
		"# See the environment README.md for details",
		"# Import this file to create your Zerops project",
	)
	for line := range strings.SplitSeq(content, "\n") {
		result = append(result, line)
		trimmed := strings.TrimSpace(line)
		// Add a comment after every substantive line to ensure ratio.
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") && strings.Contains(trimmed, ":") {
			result = append(result, "  # "+trimmed)
		}
	}
	return strings.Join(result, "\n")
}

func TestCheckRecipeFinalize_ValidOutput(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	writeRecipeFiles(t, dir, plan)

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result == nil {
		t.Fatal("expected non-nil result")
	}
	if !result.Passed {
		t.Errorf("expected all checks to pass:")
		for _, c := range result.Checks {
			if c.Status == "fail" {
				t.Errorf("  %s: %s", c.Name, c.Detail)
			}
		}
	}
}

func TestCheckRecipeFinalize_MissingFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	// Don't write any files.

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.Passed {
		t.Error("expected checks to fail when files are missing")
	}

	// Count file existence failures.
	failCount := 0
	for _, c := range result.Checks {
		if c.Status == "fail" {
			failCount++
		}
	}
	// Should have at least 13 file failures (1 main README + 6 import.yaml + 6 env README).
	if failCount < 13 {
		t.Errorf("expected at least 13 failures, got %d", failCount)
	}
}

func TestCheckRecipeFinalize_InvalidYAML(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	writeRecipeFiles(t, dir, plan)

	// Overwrite one import.yaml with invalid YAML.
	badPath := filepath.Join(dir, workflow.EnvFolder(0), "import.yaml")
	if err := os.WriteFile(badPath, []byte("{{invalid yaml"), 0o644); err != nil {
		t.Fatal(err)
	}

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.Passed {
		t.Error("expected checks to fail with invalid YAML")
	}

	found := false
	for _, c := range result.Checks {
		if c.Status == "fail" && c.Name == fmt.Sprintf("%s_import_valid_yaml", workflow.EnvFolder(0)) {
			found = true
			break
		}
	}
	if !found {
		t.Error("expected valid_yaml check to fail")
	}
}

func TestCheckRecipeFinalize_SharedSecret(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	plan.Research.NeedsAppSecret = true
	plan.Research.AppSecretKey = "SECRET_KEY"

	writeRecipeFiles(t, dir, plan)

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Generated templates put shared secret in project.envVariables.
	for _, c := range result.Checks {
		if c.Status == "fail" && strings.Contains(c.Name, "shared_secret") {
			t.Errorf("shared secret check should pass: %s", c.Detail)
		}
	}
}

func TestCheckRecipeFinalize_StartWithoutCode(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()
	writeRecipeFiles(t, dir, plan)

	// Inject startWithoutCode into env 0 import.yaml.
	env0Path := filepath.Join(dir, workflow.EnvFolder(0), "import.yaml")
	data, err := os.ReadFile(env0Path)
	if err != nil {
		t.Fatal(err)
	}
	// Add startWithoutCode after the first hostname line.
	modified := strings.Replace(string(data), "type: bun@1\n", "type: bun@1\n    startWithoutCode: true\n", 1)
	if err := os.WriteFile(env0Path, []byte(modified), 0o644); err != nil {
		t.Fatal(err)
	}

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	found := false
	for _, c := range result.Checks {
		if c.Status == "fail" && strings.Contains(c.Name, "no_start_without_code") {
			found = true
			break
		}
	}
	if !found {
		t.Error("expected startWithoutCode check to fail")
	}
}

func TestCheckSectionHeadingComments(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		content string
		wantOK  bool
	}{
		{
			name:    "no headings",
			content: "# Installs deps for production.\nservices:\n  - hostname: app\n",
			wantOK:  true,
		},
		{
			name:    "separator line",
			content: "# ---------------------------------------------------\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "heading with dashes",
			content: "# -- Dev Runtime --\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "heading with equals",
			content: "# == Database ==\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "short dashes ok",
			content: "# --\nservices:\n",
			wantOK:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			checks := checkSectionHeadingComments(tt.content, "test")
			passed := true
			for _, c := range checks {
				if c.Status == statusFail {
					passed = false
				}
			}
			if passed != tt.wantOK {
				t.Errorf("checkSectionHeadingComments() passed=%v, want %v", passed, tt.wantOK)
			}
		})
	}
}

func TestCheckCrossEnvReferences(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		content string
		wantOK  bool
	}{
		{
			name:    "no cross-env refs",
			content: "# Production app — dedicated CPU pins cores.\nservices:\n  - hostname: app\n",
			wantOK:  true,
		},
		{
			name:    "env N in comment",
			content: "# Same as env 0.\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "envs range",
			content: "# Same production build as envs 4-5.\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "parenthesized reference",
			content: "# Consider HA (env 5) for higher durability.\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "no-op in env 4",
			content: "# zsc execOnce is a no-op here but load-bearing in env 4.\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "environment variables prose ok",
			content: "# Laravel reads environment variables at boot.\nservices:\n",
			wantOK:  true,
		},
		{
			name:    "PHP 8.4 version mention ok",
			content: "# php-nginx@8.4 runs PHP 8.4 with FPM.\nservices:\n",
			wantOK:  true,
		},
		{
			name:    "environment 3 phrasing",
			content: "# Mirrors what environment 3 does for staging.\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "case-insensitive Env",
			content: "# See Env 0 for the dev workflow.\nservices:\n",
			wantOK:  false,
		},
		{
			name:    "reference only inside comment lines",
			content: "  DB_PORT: env5_port\n",
			wantOK:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			checks := checkCrossEnvReferences(tt.content, "test")
			passed := true
			for _, c := range checks {
				if c.Status == statusFail {
					passed = false
				}
			}
			if passed != tt.wantOK {
				t.Errorf("checkCrossEnvReferences() passed=%v, want %v (content=%q)", passed, tt.wantOK, tt.content)
			}
		})
	}
}

func TestValidateImportYAML_DuplicateKeys(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		content string
		wantOK  bool
	}{
		{
			name: "no duplicates",
			content: `project:
  name: test-dev
  envVariables:
    APP_KEY: secret
    APP_URL: https://example.com
services:
  - hostname: app
    type: bun@1
`,
			wantOK: true,
		},
		{
			name: "duplicate env var key",
			content: `project:
  name: test-dev
  envVariables:
    APP_KEY: secret
    APP_URL: https://example.com
    APP_KEY: other
services:
  - hostname: app
    type: bun@1
`,
			wantOK: false,
		},
		{
			name: "duplicate top-level key",
			content: `project:
  name: test-dev
project:
  name: test-dev2
services:
  - hostname: app
    type: bun@1
`,
			wantOK: false,
		},
	}

	plan := testFinalizePlan()
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			checks := validateImportYAML(tt.content, plan, 0, "test")
			hasDupeCheck := false
			for _, c := range checks {
				if c.Status == statusFail && strings.Contains(c.Name, "duplicate_keys") {
					hasDupeCheck = true
				}
			}
			if !tt.wantOK && !hasDupeCheck {
				t.Errorf("expected duplicate_keys check to fail for %q", tt.name)
			}
			if tt.wantOK && hasDupeCheck {
				t.Errorf("expected duplicate_keys check to pass for %q", tt.name)
			}
		})
	}
}

func TestCheckRecipeFinalize_CommentRatio(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()

	// Write template files — platform comments only, below 30% threshold.
	files := workflow.BuildFinalizeOutput(plan)
	for relPath, content := range files {
		fullPath := filepath.Join(dir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Template baseline has platform comments only — comment_ratio SHOULD fail
	// at 30% threshold. This forces the agent to add framework-specific comments.
	hasCommentFail := false
	for _, c := range result.Checks {
		if c.Status == "fail" && strings.Contains(c.Name, "comment_ratio") {
			hasCommentFail = true
			break
		}
	}
	if !hasCommentFail {
		t.Error("expected comment_ratio to fail for template-only output (agent must enrich)")
	}
}

func TestCheckRecipeFinalize_HandWrittenFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	plan := testFinalizePlan()

	// Write hand-crafted import.yaml for env 0 WITHOUT zeropsSetup/buildFromGit.
	// This simulates the agent rewriting auto-generated files from scratch.
	handwritten := `# AI agent environment
project:
  name: bun-hello-world-agent
services:
  # Some comment about the app
  - hostname: app
    type: bun@1
    priority: 10
  # Some comment about the DB
  - hostname: db
    type: postgresql@16
    priority: 10
    mode: NON_HA
`
	env0Dir := filepath.Join(dir, workflow.EnvFolder(0))
	if err := os.MkdirAll(env0Dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(env0Dir, "import.yaml"), []byte(handwritten), 0o644); err != nil {
		t.Fatal(err)
	}
	// Write valid README for env 0.
	if err := os.WriteFile(filepath.Join(env0Dir, "README.md"), []byte("# Test"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Write remaining files from template so other checks don't mask our failures.
	files := workflow.BuildFinalizeOutput(plan)
	for relPath, content := range files {
		if strings.HasPrefix(relPath, workflow.EnvFolder(0)+"/") {
			continue // skip env 0 — we wrote our hand-crafted version
		}
		fullPath := filepath.Join(dir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if filepath.Base(relPath) == "import.yaml" {
			content = addCommentsToYAML(content)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	checker := checkRecipeFinalize(dir)
	result, err := checker(context.Background(), plan, &workflow.RecipeState{OutputDir: dir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should fail: app service missing zeropsSetup+buildFromGit.
	foundSetupGit := false
	// Should fail: env 0 missing appdev/appstage hostnames.
	foundDevHost := false
	foundStageHost := false

	for _, c := range result.Checks {
		if c.Status == "fail" {
			if strings.Contains(c.Name, "setup_git") && strings.Contains(c.Detail, "missing zeropsSetup") {
				foundSetupGit = true
			}
			if strings.Contains(c.Name, "appdev_exists") {
				foundDevHost = true
			}
			if strings.Contains(c.Name, "appstage_exists") {
				foundStageHost = true
			}
		}
	}

	if !foundSetupGit {
		t.Error("expected setup_git check to fail for hand-written file missing zeropsSetup+buildFromGit")
	}
	if !foundDevHost {
		t.Error("expected appdev_exists check to fail — env 0 should have appdev, not bare app")
	}
	if !foundStageHost {
		t.Error("expected appstage_exists check to fail — env 0 should have appstage")
	}
}
