package sync

import (
	"bytes"
	"fmt"
	"os/exec"
	"strings"
)

// PublishOpts holds recipe metadata for template placeholder replacement.
type PublishOpts struct {
	Slug        string // e.g. "laravel-minimal"
	PrettyName  string // e.g. "Laravel Minimal"
	Software    string // e.g. "Laravel"
	Description string // one-line description for intro
	Tags        string // e.g. "php" for recipe filtering
	CoverSVG    string // e.g. "cover-laravel.svg" (empty = omit)
}

// templatePlaceholders maps template placeholders to PublishOpts values.
func templatePlaceholders(opts PublishOpts) map[string]string {
	return map[string]string{
		"PLACEHOLDER_PRETTY_RECIPE_NAME": opts.PrettyName,
		"PLACEHOLDER_RECIPE_SOFTWARE":    opts.Software,
		"PLACEHOLDER_RECIPE_DESCRIPTION": opts.Description,
		"PLACEHOLDER_RECIPE_DIRECTORY":   opts.Slug,
		"PLACEHOLDER_RECIPE_TAGS":        opts.Tags,
		"PLACEHOLDER_PRETTY_RECIPE_TAGS": opts.Tags,
		"PLACEHOLDER_COVER_SVG":          opts.CoverSVG,
		"PLACEHOLDER_PROJECT_NAME":       opts.Slug,
	}
}

// applyPlaceholders replaces all PLACEHOLDER_ values in content.
func applyPlaceholders(content string, placeholders map[string]string) string {
	for k, v := range placeholders {
		content = strings.ReplaceAll(content, k, v)
	}
	return content
}

// PublishRecipe publishes recipe environment files to zeropsio/recipes as a PR.
// Fetches the _template from the recipes repo, applies placeholders, then
// overlays the generated import.yaml files from the recipe output.
func PublishRecipe(cfg *Config, slug, sourceDir string, opts PublishOpts, dryRun bool) (PushResult, error) {
	// Collect our generated import.yaml files.
	localFiles, err := CollectRecipeFiles(sourceDir, slug)
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("collect files: %w", err)
	}
	if len(localFiles) == 0 {
		return PushResult{Slug: slug, Status: Skipped, Reason: "no files found"}, nil
	}

	repo := cfg.Push.Recipes.RecipesRepo
	if repo == "" {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("recipes_repo not configured")
	}

	gh := &GH{Repo: repo}
	opts.Slug = slug
	placeholders := templatePlaceholders(opts)

	// Fetch _template files from the recipes repo.
	templateFiles, err := fetchTemplateFiles(gh, "_template")
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("fetch template: %w", err)
	}

	// Build final file map: template files with placeholders replaced,
	// then overlay our generated import.yaml files.
	files := make(map[string]string, len(templateFiles)+len(localFiles))

	// Apply template files, remapping _template/ → {slug}/
	for path, content := range templateFiles {
		// Skip .human marker file.
		if strings.HasSuffix(path, "/.human") || path == ".human" {
			continue
		}
		// Remap path: _template/X → {slug}/X
		newPath := slug + "/" + strings.TrimPrefix(path, "_template/")
		// Apply placeholders to content.
		files[newPath] = applyPlaceholders(content, placeholders)
	}

	// Overlay our generated files (import.yaml, README.md from recipe output).
	// Our import.yaml replaces the template stub; our README.md is skipped
	// since the template README is better (has markers, deploy links).
	for path, content := range localFiles {
		if strings.HasSuffix(path, "/import.yaml") {
			files[path] = content
		}
		// Skip README.md from local — template READMEs have correct markers.
		// Exception: root README.md if template doesn't cover intro well enough
		// could be overlaid here in the future.
	}

	if dryRun {
		var paths []string
		for p := range files {
			paths = append(paths, p)
		}
		return PushResult{
			Slug:   slug,
			Status: DryRun,
			Diff:   fmt.Sprintf("would commit %d files:\n  %s", len(files), strings.Join(paths, "\n  ")),
		}, nil
	}

	// Get base SHA.
	headSHA, err := gh.DefaultBranchSHA()
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("get HEAD SHA: %w", err)
	}

	// Create branch.
	branch := fmt.Sprintf("%s/recipe-%s-%s", cfg.Push.Recipes.BranchPrefix, slug, today())
	if err := gh.CreateBranch(branch); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create branch: %w", err)
	}

	// Create tree with all files.
	treeSHA, err := gh.CreateTree(headSHA, files)
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create tree: %w", err)
	}

	// Create commit.
	commitMsg := fmt.Sprintf("%s: publish %s environments", cfg.Push.Recipes.CommitPrefix, slug)
	commitSHA, err := gh.CreateCommit(treeSHA, headSHA, commitMsg)
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create commit: %w", err)
	}

	// Update branch ref.
	if err := gh.UpdateRef(branch, commitSHA); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("update ref: %w", err)
	}

	// Create PR.
	title := fmt.Sprintf("recipe: publish %s", slug)
	body := fmt.Sprintf("Publish %s recipe environments (%d files).\n\nGenerated by ZCP recipe workflow using _template.", slug, len(files))
	prURL, err := gh.CreatePR(branch, title, body)
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create PR: %w", err)
	}

	return PushResult{Slug: slug, Status: Created, PRURL: prURL}, nil
}

// fetchTemplateFiles reads all files from the _template directory in the recipes repo.
// Returns a map of relative paths (from repo root) to content.
func fetchTemplateFiles(gh *GH, templateDir string) (map[string]string, error) {
	files := make(map[string]string)

	// List top-level entries in _template.
	entries, err := gh.ListDirectory(templateDir)
	if err != nil {
		return nil, fmt.Errorf("list template dir: %w", err)
	}

	for _, entry := range entries {
		entryPath := templateDir + "/" + entry

		// Try reading as file first.
		content, _, readErr := gh.ReadFile(entryPath)
		if readErr == nil {
			files[entryPath] = content
			continue
		}

		// Must be a directory — list its contents.
		subEntries, listErr := gh.ListDirectory(entryPath)
		if listErr != nil {
			continue
		}
		for _, sub := range subEntries {
			subPath := entryPath + "/" + sub
			subContent, _, subReadErr := gh.ReadFile(subPath)
			if subReadErr == nil {
				files[subPath] = subContent
			}
		}
	}

	return files, nil
}

// PushAppSource pushes the app source directory to the recipe app repo.
// Uses git to add remote + push. The app dir must have .git initialized.
func PushAppSource(cfg *Config, slug, appDir string, dryRun bool) (PushResult, error) {
	org := cfg.Push.Recipes.Org
	repoName := slug + "-app"
	fullRepo := org + "/" + repoName
	repoURL := "https://github.com/" + fullRepo + ".git"

	if dryRun {
		return PushResult{Slug: slug, Status: DryRun, Diff: fmt.Sprintf("would push %s to %s", appDir, fullRepo)}, nil
	}

	// Verify .git exists.
	if !hasGitDir(appDir) {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("no .git in %s — run git init first", appDir)
	}

	// Add remote (ignore error if already exists).
	_ = runGit(appDir, "remote", "add", "origin", repoURL)
	// Update URL in case remote exists with wrong URL.
	_ = runGit(appDir, "remote", "set-url", "origin", repoURL)

	// Stage all, commit if needed, push.
	_ = runGit(appDir, "add", "-A")
	_ = runGit(appDir, "diff-index", "--quiet", "HEAD", "--")
	_ = runGit(appDir, "commit", "-q", "-m", "recipe: "+slug)

	if err := runGit(appDir, "push", "-u", "origin", "HEAD"); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("git push: %w", err)
	}

	return PushResult{Slug: slug, Status: Created, PRURL: "https://github.com/" + fullRepo}, nil
}

// runGit runs a git command in the given directory.
func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...) //nolint:noctx // short-lived CLI command
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git %s: %w\nstderr: %s", args[0], err, stderr.String())
	}
	return nil
}

// CreateRecipeRepo creates a new public repo in the recipe apps org.
func CreateRecipeRepo(cfg *Config, slug string, dryRun bool) (PushResult, error) {
	org := cfg.Push.Recipes.Org
	repoName := slug + "-app"
	fullRepo := org + "/" + repoName

	gh := &GH{}
	if gh.RepoExists(fullRepo) {
		return PushResult{Slug: slug, Status: Skipped, Reason: fullRepo + " already exists"}, nil
	}

	if dryRun {
		return PushResult{Slug: slug, Status: DryRun, Diff: "would create " + fullRepo}, nil
	}

	if err := gh.CreateOrgRepo(org, repoName); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create repo: %w", err)
	}

	return PushResult{Slug: slug, Status: Created, PRURL: "https://github.com/" + fullRepo}, nil
}
