package sync

import (
	"fmt"
	"strings"
)

// PublishRecipe publishes recipe environment files to zeropsio/recipes as a PR.
func PublishRecipe(cfg *Config, slug, sourceDir string, dryRun bool) (PushResult, error) {
	files, err := CollectRecipeFiles(sourceDir, slug)
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("collect files: %w", err)
	}

	if len(files) == 0 {
		return PushResult{Slug: slug, Status: Skipped, Reason: "no files found in environments/"}, nil
	}

	repo := cfg.Push.Recipes.RecipesRepo
	if repo == "" {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("recipes_repo not configured in .sync.yaml")}, nil
	}

	gh := &GH{Repo: repo}

	if dryRun {
		var paths []string
		for p := range files {
			paths = append(paths, p)
		}
		return PushResult{
			Slug:   slug,
			Status: DryRun,
			Diff:   fmt.Sprintf("would commit %d files:\n  %s", len(files), strings.Join(paths, "\n  ")),
		}, nil
	}

	// Get base SHA.
	headSHA, err := gh.DefaultBranchSHA()
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("get HEAD SHA: %w", err)}, nil
	}

	// Create branch.
	branch := fmt.Sprintf("%s/recipe-%s-%s", cfg.Push.Recipes.BranchPrefix, slug, today())
	if err := gh.CreateBranch(branch); err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create branch: %w", err)}, nil
	}

	// Create tree with all files.
	treeSHA, err := gh.CreateTree(headSHA, files)
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create tree: %w", err)}, nil
	}

	// Create commit.
	commitMsg := fmt.Sprintf("%s: publish %s environments", cfg.Push.Recipes.CommitPrefix, slug)
	commitSHA, err := gh.CreateCommit(treeSHA, headSHA, commitMsg)
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create commit: %w", err)}, nil
	}

	// Update branch ref.
	if err := gh.UpdateRef(branch, commitSHA); err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("update ref: %w", err)}, nil
	}

	// Create PR.
	title := fmt.Sprintf("recipe: publish %s", slug)
	body := fmt.Sprintf("Publish %s recipe environments (%d files).\n\nGenerated by ZCP recipe workflow.", slug, len(files))
	prURL, err := gh.CreatePR(branch, title, body)
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create PR: %w", err)}, nil
	}

	return PushResult{Slug: slug, Status: Created, PRURL: prURL}, nil
}

// CreateRecipeRepo creates a new public repo in the recipe apps org.
func CreateRecipeRepo(cfg *Config, slug string, dryRun bool) (PushResult, error) {
	org := cfg.Push.Recipes.Org
	repoName := slug + "-app"
	fullRepo := org + "/" + repoName

	gh := &GH{}
	if gh.RepoExists(fullRepo) {
		return PushResult{Slug: slug, Status: Skipped, Reason: fullRepo + " already exists"}, nil
	}

	if dryRun {
		return PushResult{Slug: slug, Status: DryRun, Diff: "would create " + fullRepo}, nil
	}

	if err := gh.CreateOrgRepo(org, repoName); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create repo: %w", err)
	}

	return PushResult{Slug: slug, Status: Created, PRURL: "https://github.com/" + fullRepo}, nil
}
