package sync

import (
	"bytes"
	"fmt"
	"os/exec"
	"strings"
)

// PublishRecipe publishes recipe environment files to zeropsio/recipes as a PR.
func PublishRecipe(cfg *Config, slug, sourceDir string, dryRun bool) (PushResult, error) {
	files, err := CollectRecipeFiles(sourceDir, slug)
	if err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("collect files: %w", err)
	}

	if len(files) == 0 {
		return PushResult{Slug: slug, Status: Skipped, Reason: "no files found in environments/"}, nil
	}

	repo := cfg.Push.Recipes.RecipesRepo
	if repo == "" {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("recipes_repo not configured in .sync.yaml")}, nil
	}

	gh := &GH{Repo: repo}

	if dryRun {
		var paths []string
		for p := range files {
			paths = append(paths, p)
		}
		return PushResult{
			Slug:   slug,
			Status: DryRun,
			Diff:   fmt.Sprintf("would commit %d files:\n  %s", len(files), strings.Join(paths, "\n  ")),
		}, nil
	}

	// Get base SHA.
	headSHA, err := gh.DefaultBranchSHA()
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("get HEAD SHA: %w", err)}, nil
	}

	// Create branch.
	branch := fmt.Sprintf("%s/recipe-%s-%s", cfg.Push.Recipes.BranchPrefix, slug, today())
	if err := gh.CreateBranch(branch); err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create branch: %w", err)}, nil
	}

	// Create tree with all files.
	treeSHA, err := gh.CreateTree(headSHA, files)
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create tree: %w", err)}, nil
	}

	// Create commit.
	commitMsg := fmt.Sprintf("%s: publish %s environments", cfg.Push.Recipes.CommitPrefix, slug)
	commitSHA, err := gh.CreateCommit(treeSHA, headSHA, commitMsg)
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create commit: %w", err)}, nil
	}

	// Update branch ref.
	if err := gh.UpdateRef(branch, commitSHA); err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("update ref: %w", err)}, nil
	}

	// Create PR.
	title := fmt.Sprintf("recipe: publish %s", slug)
	body := fmt.Sprintf("Publish %s recipe environments (%d files).\n\nGenerated by ZCP recipe workflow.", slug, len(files))
	prURL, err := gh.CreatePR(branch, title, body)
	if err != nil {
		return PushResult{Slug: slug, Status: Error, Err: fmt.Errorf("create PR: %w", err)}, nil
	}

	return PushResult{Slug: slug, Status: Created, PRURL: prURL}, nil
}

// PushAppSource pushes the app source directory to the recipe app repo.
// Uses git to add remote + push. The app dir must have .git initialized.
func PushAppSource(cfg *Config, slug, appDir string, dryRun bool) (PushResult, error) {
	org := cfg.Push.Recipes.Org
	repoName := slug + "-app"
	fullRepo := org + "/" + repoName
	repoURL := "https://github.com/" + fullRepo + ".git"

	if dryRun {
		return PushResult{Slug: slug, Status: DryRun, Diff: fmt.Sprintf("would push %s to %s", appDir, fullRepo)}, nil
	}

	// Verify .git exists.
	if !hasGitDir(appDir) {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("no .git in %s — run git init first", appDir)
	}

	// Add remote (ignore error if already exists).
	_ = runGit(appDir, "remote", "add", "origin", repoURL)
	// Update URL in case remote exists with wrong URL.
	_ = runGit(appDir, "remote", "set-url", "origin", repoURL)

	// Stage all, commit if needed, push.
	_ = runGit(appDir, "add", "-A")
	_ = runGit(appDir, "diff-index", "--quiet", "HEAD", "--") // check if clean
	// Commit only if there are changes (ignore error if nothing to commit).
	_ = runGit(appDir, "commit", "-q", "-m", "recipe: "+slug)

	if err := runGit(appDir, "push", "-u", "origin", "HEAD"); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("git push: %w", err)
	}

	return PushResult{Slug: slug, Status: Created, PRURL: "https://github.com/" + fullRepo}, nil
}

// runGit runs a git command in the given directory.
func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...) //nolint:gosec,noctx // short-lived CLI command
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git %s: %w\nstderr: %s", args[0], err, stderr.String())
	}
	return nil
}

// CreateRecipeRepo creates a new public repo in the recipe apps org.
func CreateRecipeRepo(cfg *Config, slug string, dryRun bool) (PushResult, error) {
	org := cfg.Push.Recipes.Org
	repoName := slug + "-app"
	fullRepo := org + "/" + repoName

	gh := &GH{}
	if gh.RepoExists(fullRepo) {
		return PushResult{Slug: slug, Status: Skipped, Reason: fullRepo + " already exists"}, nil
	}

	if dryRun {
		return PushResult{Slug: slug, Status: DryRun, Diff: "would create " + fullRepo}, nil
	}

	if err := gh.CreateOrgRepo(org, repoName); err != nil {
		return PushResult{Slug: slug, Status: Error}, fmt.Errorf("create repo: %w", err)
	}

	return PushResult{Slug: slug, Status: Created, PRURL: "https://github.com/" + fullRepo}, nil
}
