#!/usr/bin/env bash
# measure_calibration_bars.sh — evaluate v35 run against the calibration
# bars declared in docs/zcprecipator2/05-regression/calibration-bars-v35.md
#
# Usage: scripts/measure_calibration_bars.sh <session-log> <deliverable-tree>
#
# Session log: JSONL trace of the workflow session (the full zerops_workflow
# call / response pairs). Used by §C-* bars that need round-count evidence
# (e.g. deploy.readmes rounds, finalize rounds).
# Deliverable tree: the recipe output directory (apidev/, appdev/, workerdev/,
# environments/, ZCP_CONTENT_MANIFEST.json). Used by §A-* / §B-* / §P-* bars
# that evaluate the shipped content.
#
# Status: **SCAFFOLD**. C-14 lands the driver skeleton + per-bar section
# markers + the Python evidence-extractor dependency. Full bar-by-bar
# evaluation logic is deferred to post-v35 — the first real v35 session
# log is needed to calibrate the session-log parsers, and several bars
# (§Q quality bars) require the v35 deliverable to be authored before
# the measurement logic can be finalized. Each bar's evaluator is a
# stubbed section; fill in the grep/jq/Python call + PASS/FAIL emission
# as the data arrives.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <session-log> <deliverable-tree>" >&2
  echo "" >&2
  echo "Produces: reports/v35-measurement-<timestamp>.md" >&2
  exit 2
fi

SESSION_LOG="$1"
DELIVERABLE_TREE="$2"
TIMESTAMP=$(date +%Y%m%dT%H%M%S)
REPORT="reports/v35-measurement-${TIMESTAMP}.md"

mkdir -p reports

for required in "$SESSION_LOG" "$DELIVERABLE_TREE"; do
  if [[ ! -e "$required" ]]; then
    echo "missing input: $required" >&2
    exit 1
  fi
done

EVIDENCE_HELPER="$(dirname "$0")/extract_calibration_evidence.py"
if [[ ! -x "$EVIDENCE_HELPER" ]]; then
  chmod +x "$EVIDENCE_HELPER" 2>/dev/null || true
fi

# --- Report header ----------------------------------------------------

cat > "$REPORT" <<EOF
# v35 calibration-bar measurement — $TIMESTAMP

Session log: \`$SESSION_LOG\`
Deliverable tree: \`$DELIVERABLE_TREE\`

Columns per bar: **PASS** / **FAIL** / **SKIP** (unevaluated this run).

---

EOF

# --- §1 session-flow bars (C-1..C-N) ---------------------------------
# TODO(post-v35): wire each C-* bar. Session-log parsers live in
# extract_calibration_evidence.py.
cat >> "$REPORT" <<'EOF'
## §1 Session flow

- **C-1 deploy.readmes rounds ≤ 2**: SKIP (post-v35 data required).
- **C-2 finalize rounds ≤ 2**: SKIP (post-v35 data required).
- **C-6 out-of-order substep completes = 0**: SKIP (engine guard verified via unit tests; session-log cross-check deferred).
- **C-11 TodoWrite full-rewrite detection**: SKIP (parser in extract_calibration_evidence.py:extract_todowrite_rewrites; deferred).

EOF

# --- §2 scaffold-quality bars (A-*) -----------------------------------
# TODO(post-v35): static scans on the deliverable tree.
cat >> "$REPORT" <<'EOF'
## §2 Scaffold quality

- **A-1 every scaffolded codebase has a valid zerops.yaml**: SKIP.
- **A-2 env-var references resolve against platform vars**: SKIP.
- **A-3 no scaffold-self-referential gotchas**: SKIP.

EOF

# --- §3 writer-quality bars (B-*) -------------------------------------
# TODO(post-v35): writer subagent output scans.
cat >> "$REPORT" <<'EOF'
## §3 Writer quality

- **B-1..B-8 atom-tree invariants**: enforced at build-time (C-13).
  Evaluate tools/lint/recipe_atom_lint output vs production tree.

EOF

# --- §4 editorial-review bars (E-*) -----------------------------------
cat >> "$REPORT" <<'EOF'
## §4 Editorial review

- **E-1 editorial-review dispatched at close**: SKIP.
- **E-2 reclassification delta == 0 post-inline-fix**: SKIP.
- **E-3 citation coverage ≥ 80%**: SKIP.

EOF

# --- §5..§11 remaining bars ------------------------------------------
cat >> "$REPORT" <<'EOF'
## §5..§11 remaining bars

All SKIP pending post-v35 session log + deliverable.

EOF

# --- Report footer ----------------------------------------------------
cat >> "$REPORT" <<EOF
---

Generated by \`scripts/measure_calibration_bars.sh\` (scaffold — full
implementation lands post-v35 when session-log format + Q-bar evaluators
are calibrated against real data).
EOF

echo "wrote $REPORT" >&2
