package ops

import (
	"fmt"
	"strings"

	"github.com/zeropsio/zcp/internal/platform"
)

// ServiceEnvGroup holds a service hostname and its env vars for .env file generation.
type ServiceEnvGroup struct {
	Hostname string
	Type     string
	Vars     []platform.EnvVar
}

// FormatEnvFile generates .env file content from discovered service env vars.
// Groups vars by service with comments. Adds VPN hint header.
func FormatEnvFile(groups []ServiceEnvGroup, projectID string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by ZCP from zerops_discover\n")
	sb.WriteString(fmt.Sprintf("# VPN required: zcli vpn up %s\n", projectID))
	sb.WriteString("# WARNING: Contains secrets. Do not commit.\n\n")

	for i, g := range groups {
		if i > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString(fmt.Sprintf("# %s (%s)\n", g.Hostname, g.Type))
		for _, v := range g.Vars {
			sb.WriteString(fmt.Sprintf("%s_%s=%s\n", g.Hostname, v.Key, v.Content))
		}
	}

	return sb.String()
}
