package ops

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/zeropsio/zcp/internal/platform"
)

// EnvDotenvResult contains the result of .env file generation.
type EnvDotenvResult struct {
	Path      string `json:"path"`
	Services  int    `json:"services"`
	Variables int    `json:"variables"`
}

// refPattern matches a full ${hostname_varName} cross-service reference.
// In Zerops, ${...} is ONLY for cross-service refs — project-level env vars are auto-injected.
var refPattern = regexp.MustCompile(`^\$\{([a-zA-Z][a-zA-Z0-9]*_[a-zA-Z_][a-zA-Z0-9_]*)\}$`)

// EnvGenerateDotenv reads zerops.yaml envVariables for a service, resolves ${hostname_varName}
// cross-service references by fetching actual values from managed services, appends project-level
// env vars, and writes a .env file. The LLM never sees secret values — ZCP resolves internally.
func EnvGenerateDotenv(
	ctx context.Context,
	client platform.Client,
	projectID string,
	hostname string,
	workingDir string,
) (*EnvDotenvResult, error) {
	if hostname == "" {
		return nil, platform.NewPlatformError(platform.ErrInvalidParameter,
			"serviceHostname is required for generate-dotenv",
			"Specify which service's zerops.yaml envVariables to resolve")
	}

	if workingDir == "" {
		workingDir = "."
	}

	doc, err := ParseZeropsYml(workingDir)
	if err != nil {
		return nil, fmt.Errorf("generate-dotenv: %w", err)
	}

	entry := doc.FindEntry(hostname)
	if entry == nil {
		return nil, platform.NewPlatformError(platform.ErrInvalidParameter,
			fmt.Sprintf("no setup entry for %q in zerops.yaml", hostname),
			"Check that zerops.yaml has a setup: entry matching the service hostname")
	}

	if len(entry.EnvVariables) == 0 {
		return nil, platform.NewPlatformError(platform.ErrInvalidParameter,
			fmt.Sprintf("setup %q has no envVariables in zerops.yaml", hostname),
			"Add envVariables to zerops.yaml first")
	}

	// Resolve zerops.yaml envVariables — cross-service refs only.
	serviceEnvCache := make(map[string][]platform.EnvVar)
	resolved := make(map[string]string, len(entry.EnvVariables))
	var unresolvedKeys []string

	for envName, rawValue := range entry.EnvVariables {
		match := refPattern.FindStringSubmatch(rawValue)
		if match == nil {
			// Static value (not a cross-service reference) — use as-is.
			resolved[envName] = rawValue
			continue
		}

		// Cross-service reference: ${hostname_varName}.
		refBody := match[1]
		svcHostname, varName, _ := strings.Cut(refBody, "_")

		if _, cached := serviceEnvCache[svcHostname]; !cached {
			services, listErr := client.ListServices(ctx, projectID)
			if listErr != nil {
				return nil, fmt.Errorf("list services: %w", listErr)
			}
			svc, resolveErr := resolveServiceID(services, svcHostname)
			if resolveErr != nil {
				return nil, resolveErr
			}
			envs, getErr := client.GetServiceEnv(ctx, svc.ID)
			if getErr != nil {
				return nil, fmt.Errorf("fetch env vars for %s: %w", svcHostname, getErr)
			}
			serviceEnvCache[svcHostname] = envs
		}

		val := findEnvValue(serviceEnvCache[svcHostname], varName)
		if val == "" {
			unresolvedKeys = append(unresolvedKeys, envName)
		} else {
			resolved[envName] = val
		}
	}

	if len(unresolvedKeys) > 0 {
		return nil, platform.NewPlatformError(platform.ErrInvalidParameter,
			fmt.Sprintf("could not resolve env vars: %s", strings.Join(unresolvedKeys, ", ")),
			"Check that referenced services are running and have the expected env var keys")
	}

	// Append project-level env vars (auto-injected in containers, needed in .env for local dev).
	projectEnvs, err := client.GetProjectEnv(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("fetch project env vars: %w", err)
	}
	for _, pe := range projectEnvs {
		if _, exists := resolved[pe.Key]; !exists {
			resolved[pe.Key] = pe.Content
		}
	}

	// Write .env file.
	var sb strings.Builder
	sb.WriteString("# Generated by ZCP from zerops.yaml envVariables\n")
	sb.WriteString("# WARNING: Contains secrets. Do not commit.\n\n")
	for envName, val := range resolved {
		sb.WriteString(envName)
		sb.WriteByte('=')
		sb.WriteString(val)
		sb.WriteByte('\n')
	}

	envPath := filepath.Join(workingDir, ".env")
	if err := os.WriteFile(envPath, []byte(sb.String()), 0600); err != nil {
		return nil, fmt.Errorf("write .env: %w", err)
	}

	return &EnvDotenvResult{
		Path:      envPath,
		Services:  len(serviceEnvCache),
		Variables: len(resolved),
	}, nil
}

func findEnvValue(envs []platform.EnvVar, key string) string {
	for _, e := range envs {
		if e.Key == key {
			return e.Content
		}
	}
	return ""
}
