// Tests for: ops/env_export.go — .env file generation from zerops_discover.
package ops

import (
	"strings"
	"testing"

	"github.com/zeropsio/zcp/internal/platform"
)

func TestFormatEnvFile_SingleService(t *testing.T) {
	t.Parallel()

	groups := []ServiceEnvGroup{
		{
			Hostname: "db",
			Type:     "postgresql@16",
			Vars: []platform.EnvVar{
				{Key: "host", Content: "db"},
				{Key: "port", Content: "5432"},
				{Key: "password", Content: "secret123"},
			},
		},
	}

	result := FormatEnvFile(groups, "proj-1")

	// Header checks.
	if !strings.Contains(result, "Generated by ZCP") {
		t.Error("expected header comment")
	}
	if !strings.Contains(result, "zcli vpn up proj-1") {
		t.Error("expected VPN hint with project ID")
	}
	if !strings.Contains(result, "Do not commit") {
		t.Error("expected commit warning")
	}

	// Service comment.
	if !strings.Contains(result, "# db (postgresql@16)") {
		t.Error("expected service comment")
	}

	// Env var lines.
	if !strings.Contains(result, "db_host=db") {
		t.Errorf("expected db_host=db, got:\n%s", result)
	}
	if !strings.Contains(result, "db_port=5432") {
		t.Errorf("expected db_port=5432")
	}
	if !strings.Contains(result, "db_password=secret123") {
		t.Errorf("expected db_password=secret123")
	}
}

func TestFormatEnvFile_MultipleServices(t *testing.T) {
	t.Parallel()

	groups := []ServiceEnvGroup{
		{
			Hostname: "db",
			Type:     "postgresql@16",
			Vars: []platform.EnvVar{
				{Key: "connectionString", Content: "postgresql://db:pass@db:5432/db"},
			},
		},
		{
			Hostname: "cache",
			Type:     "valkey@7.2",
			Vars: []platform.EnvVar{
				{Key: "host", Content: "cache"},
				{Key: "port", Content: "6379"},
			},
		},
	}

	result := FormatEnvFile(groups, "proj-2")

	if !strings.Contains(result, "# db (postgresql@16)") {
		t.Error("expected db section")
	}
	if !strings.Contains(result, "# cache (valkey@7.2)") {
		t.Error("expected cache section")
	}
	if !strings.Contains(result, "db_connectionString=postgresql://") {
		t.Error("expected db_connectionString")
	}
	if !strings.Contains(result, "cache_host=cache") {
		t.Error("expected cache_host")
	}
}

func TestFormatEnvFile_SpecialChars(t *testing.T) {
	t.Parallel()

	groups := []ServiceEnvGroup{
		{
			Hostname: "db",
			Type:     "postgresql@16",
			Vars: []platform.EnvVar{
				{Key: "password", Content: "p@ss=w0rd!$"},
			},
		},
	}

	result := FormatEnvFile(groups, "proj-1")

	// Special chars preserved as-is in .env format.
	if !strings.Contains(result, "db_password=p@ss=w0rd!$") {
		t.Errorf("expected special chars preserved, got:\n%s", result)
	}
}

func TestFormatEnvFile_IncludesS3(t *testing.T) {
	t.Parallel()

	groups := []ServiceEnvGroup{
		{
			Hostname: "storage",
			Type:     "object-storage",
			Vars: []platform.EnvVar{
				{Key: "apiUrl", Content: "https://storage.app-prg1.zerops.io"},
				{Key: "accessKeyId", Content: "AKID123"},
				{Key: "secretAccessKey", Content: "SECRET456"},
				{Key: "bucketName", Content: "mybucket"},
			},
		},
	}

	result := FormatEnvFile(groups, "proj-1")

	if !strings.Contains(result, "# storage (object-storage)") {
		t.Error("expected storage section")
	}
	if !strings.Contains(result, "storage_apiUrl=https://storage.app-prg1.zerops.io") {
		t.Error("expected storage_apiUrl")
	}
	if !strings.Contains(result, "storage_bucketName=mybucket") {
		t.Error("expected storage_bucketName")
	}
}

func TestFormatEnvFile_Empty(t *testing.T) {
	t.Parallel()

	result := FormatEnvFile(nil, "proj-1")

	if !strings.Contains(result, "Generated by ZCP") {
		t.Error("expected header even for empty groups")
	}
}
